language: r

addons:
  apt:
    packages:
      - libgit2-dev
os:
  - linux

#before_install:
# - sudo apt-get install r-base && R -h

install:
 - ./scripts/install-dependencies.sh

script:
  - ./scripts/test-unit.sh &&  ./scripts/test-acceptance.sh && ./scripts/build-and-install.R && ./scripts/test-cli.R && ./scripts/test-compare-vcf.sh
